base_model_config: mistralai/Mistral-7B-Instruct-v0.1
base_model: mistralai/Mistral-7B-Instruct-v0.1
model_type: MistralForCausalLM
tokenizer_type: LlamaTokenizer
is_mistral_derived_model: true

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: /nlp/projects/summarization/bhc_data_cleanup/prompt_baseline_instruct_debug.jsonl
    type: summarizetldr

dataset_prepared_path:
val_set_size: 0.005
output_dir: /nlp/projects/summarization/bhc_data_cleanup/mistral_weights/debug

sequence_len: 8192
sample_packing: false
pad_to_sequence_len: true

gradient_accumulation_steps: 8
micro_batch_size: 1
num_epochs: 1
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.000005

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 10
eval_steps: 100
eval_table_size:
eval_table_max_new_tokens: 128
save_steps: 100
save_strategy: steps
debug:
deepspeed: /home/ga2530/axolotl-bhc/deepspeed/zero3.json
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"
