base_model: /home/azureuser/llm/finetuned_mistral_7b/checkpoint-2000
base_model_config: /home/azureuser/llm/finetuned_mistral_7b/
model_type: MistralForCausalLM
tokenizer_type: LlamaTokenizer
is_mistral_derived_model: true

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: /home/azureuser/llm/bhc_data_cleanup/prompt_frost_esg.jsonl
    type: summarizetldr

dataset_prepared_path: /home/azureuser/llm/last_run_prepare
val_set_size: 0.005
output_dir: /home/azureuser/llm/mistral_weights/frost_esg

sequence_len: 8192
sample_packing: false
pad_to_sequence_len: true


gradient_accumulation_steps: 8
micro_batch_size: 1
num_epochs: 1
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.000005

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
auto_resume_from_checkpoints: true

local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 10
eval_steps: 500
eval_table_size:
eval_table_max_new_tokens: 128
save_steps: 500
save_strategy: steps
save_total_limit: 10
debug:
deepspeed: #/home/ga2530/axolotl-bhc/deepspeed/zero2.json
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"
